services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.example
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:80"
    depends_on: [api]
